### ISSUE TITLE
Rewrite with TypeScript

### ISSUE THREAD

**Issue by jaredpalmer** [palmerhq/the-platform#8]

**Comment by oieduardorabelo** [comment]
hey @jaredpalmer 👋, I would be interesting to work on this issue,

related to TS setup, I can think in 3 options:

1. Move to Babel 7 and use [@babel/preset-typescript](https://www.npmjs.com/package/@babel/preset-typescript) and incrementally migrate components
2. Move to TS tooling and make everything in 1 PR
3. Start with Item 1, when the migration is "finished", move from Babel to TS tooling

thanks

**Comment by crosscompile** [comment]
Nice!  I think we should be able to just use TS tooling since the current babel transforms we're using are covered by `tsc`.  To convert components incrementally we can set up the `tsconfig.json` with `allowJs` set to true, I think the steps would be:

Install our TS configs:
```bash
yarn add tsconfig-palmerhq tslint-config-palmerhq
```

Then in `tsconfig.json`:
```json
{
  "extends": "./node_modules/tsconfig-palmerhq/tsconfig.json",
  "compilerOptions": {
    "allowJs": true
  }
}
```

And in `tslint.json`:
```json
{
  "extends": "tslint-config-palmerhq"
}
```
